In [2]:
import pickle
import numpy as np

In [12]:
data_path = 'O/MM/GAFF_sc/veliparib/data/veliparib_dataset_I_NVT_cell_111_CUT'
with open(data_path, 'rb') as f:
    veli_data = pickle.load(f)

print(type(veli_data))
print(veli_data.keys())
print(type(veli_data['MD dataset']))
print(veli_data['MD dataset'].keys())
d = veli_data['MD dataset']

<class 'dict'>
dict_keys(['MD dataset', 'args_initialise_object', 'args_initialise_system', 'args_initialise_simulation'])
<class 'dict'>
dict_keys(['xyz', 'COMs', 'b', 'u', 'T', 'rbv', 'stride_save_frame', 'u_full'])


In [48]:
print('COMs', np.shape(d['COMs']))
print('xyz', d['xyz'].shape)
print('b', d['b'].shape)
print('u', d['u'].shape)
print('T', d['T'].shape)
print('u_full', d['u_full'].shape)
print(len(d['rbv']), type(d['rbv']))
print(d['stride_save_frame'])

COMs (60000, 1, 3)
xyz (60000, 272, 3)
b (60000, 3, 3)
u (60000, 1)
T (150000,)
u_full (150000, 1)
3 <class 'list'>
50


In [ ]:
# Check box vectors
print(d['b'][:])
# Turns out they're all the same! Which makes sense because the data from NVT simulation

[[[ 0.82410002  0.          0.        ]
  [-0.02862389  0.81559783  0.        ]
  [ 0.01127709 -0.0075703   3.80087566]]

 [[ 0.82410002  0.          0.        ]
  [-0.02862389  0.81559783  0.        ]
  [ 0.01127709 -0.0075703   3.80087566]]

 [[ 0.82410002  0.          0.        ]
  [-0.02862389  0.81559783  0.        ]
  [ 0.01127709 -0.0075703   3.80087566]]

 ...

 [[ 0.82410002  0.          0.        ]
  [-0.02862389  0.81559783  0.        ]
  [ 0.01127709 -0.0075703   3.80087566]]

 [[ 0.82410002  0.          0.        ]
  [-0.02862389  0.81559783  0.        ]
  [ 0.01127709 -0.0075703   3.80087566]]

 [[ 0.82410002  0.          0.        ]
  [-0.02862389  0.81559783  0.        ]
  [ 0.01127709 -0.0075703   3.80087566]]]


In [49]:
# What da heck is rbv?
for i in d['rbv']:
    print(type(i))
    print(i.shape)
print(np.sum(np.isclose(d['rbv'][2], d['rbv'][0])))

<class 'numpy.ndarray'>
(272, 3)
<class 'numpy.ndarray'>
(3, 3)
<class 'numpy.ndarray'>
(272, 3)
0


In [40]:
print(veli_data['args_initialise_object'].keys())
print(veli_data['args_initialise_simulation'].keys())
print(veli_data['args_initialise_system'].keys())

dict_keys(['PDB', 'n_atoms_mol', 'name'])
dict_keys(['rbv', 'minimise', 'T', 'timestep_ps', 'collision_rate', 'P', 'barostat_type', 'barostat_1_scaling', 'stride_barostat', 'custom_integrator'])
dict_keys(['PME_cutoff', 'removeCMMotion', 'nonbondedMethod', 'custom_EwaldErrorTolerance', 'constraints'])


In [44]:
print(veli_data['args_initialise_object'])
print(veli_data['args_initialise_system'])

{'PDB': './MM/GAFF_sc/veliparib/veliparib_I_equilibrated_cell_111.pdb', 'n_atoms_mol': 34, 'name': 'veliparib'}
{'PME_cutoff': 0.36, 'removeCMMotion': True, 'nonbondedMethod': PME, 'custom_EwaldErrorTolerance': 0.0001, 'constraints': None}


In [58]:
print(np.mean(d['T']))

300.12883819956073


In [57]:
import numpy as np
t = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]], [[10,20,30], [40,50,60], [70,80,90], [100,110,120]]])
print(t)
print(t.shape)
print(t.sum(axis=0).shape)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]
(2, 4, 3)
(4, 3)


# Outputs

In [60]:
misc_path = 'O/NN/training_results/misc/veliparib_I_111_trying_small_dataset_SC__misc_'
inv_path = 'O/NN/training_results/misc/veliparib_I_111_trying_small_dataset_SC__inv_test_'
with open(misc_path, 'rb') as f:
    misc = pickle.load(f)
with open(inv_path, 'rb') as g:
    inv = pickle.load(g)

In [ ]:
# Misc comes from:
'''
def save_the_above_(self, name : str):
        save_pickle_([
                      self.FEs,
                      self.SEs,
                      self.estimates,
                      self.evaluation_grid,
                      self.AVMD_T_f,
                      self.training_time,
                      ], name)
'''

In [70]:
print(type(misc))
print(len(misc), '\n')
for i in misc:
    print(type(i))
    if type(i) == dict:
        print(i[0].shape)
    elif type(i) == np.ndarray:
        print(i.shape)
    else:
        print(i)

<class 'list'>
6 

<class 'dict'>
(40,)
<class 'dict'>
(40,)
<class 'numpy.ndarray'>
(1, 40, 13)
<class 'numpy.ndarray'>
(40,)
<class 'numpy.ndarray'>
(2000, 1)
<class 'float'>
52.05281944672266


# Check 'A' data

In [4]:
A_npt_path = 'O/MM/molecules/A/data/NPT/A_LJ_0.8_0.8_NPT_dataset_Form_hcp_Cell_smaller_Temp_60'
with open(A_npt_path, 'rb') as f:
    A_npt = pickle.load(f)

In [13]:
print(A_npt['MD dataset']['u'].mean())

861.1874110627109
